# Generated by Django 5.2.1 on 2025-05-14 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], max_length=255)),
                ('pricing', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('capabilities', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'llm_info',
            },
        ),
        migrations.CreateModel(
            name='LLMRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('request_model', models.CharField(blank=True, max_length=255, null=True)),
                ('config_name', models.CharField(blank=True, max_length=255, null=True)),
                ('request_type', models.CharField(blank=True, max_length=255, null=True)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('input_tokens', models.IntegerField(blank=True, default=0, null=True)),
                ('output_tokens', models.IntegerField(blank=True, default=0, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('response_cost', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'llm_request_log',
            },
        ),
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(blank=True, max_length=255, null=True)),
                ('llm_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('config_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('system_behaviour', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('response_count', models.IntegerField(default=1)),
                ('config_data', models.JSONField(blank=True, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('llm_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_configurations', to='core.llminfo')),
            ],
            options={
                'db_table': 'llm_config',
            },
        ),
    ]
