class OpenAIConstants:
    TOKEN_MULTIPLIER = 4
    DEFAULT_SUGGESTION_LENGTH = 200
    HIGH_TEMPERATURE = 0.8
    LOW_TEMPERATURE = 0.2
    DEFAULT_FREQUENCY_PENALTY = 0.5
    DEFAULT_EMAIL_TYPE = "Sales"
    DEFAULT_TONE = "Professional"
    DEFAULT_MAX_COMPLETION_TOKENS = 16000
    DEFAULT_SIZE = "1024x1024"
    DEFAULT_QUALITY = "standard"
    DEFAULT_STYLE = "natural"

class AnthropicConstants:
    DEFAULT_MAX_TOKENS = 8000